version: "3.3"

services:
  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth"

networks:
  default:
    external:
      name: ${INETHI_NETWORK}