version: "3.3"

services:
  whoami:
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_API_RULE}`)"
      - "traefik.http.routers.api.service=${TRAEFIK_API_SERVICE}"
      - "traefik.http.routers.api.entrypoints=${TRAEFIK_API_ENTRYPOINT}"
      - "traefik.frontend.auth.forward.address=${FORWARD_AUTH_URL}"
      - "traefik.frontend.auth.forward.authResponseHeaders=${AUTH_RESPONSE_HEADER}"
      - traefik.frontend.auth.forward.trustForwardHeader=true

networks:
  default:
    external:
      name: ${INETHI_NETWORK}